pipelines:
  - name: allowedFailuretests
    steps:
      - name: step1aftests
        type: Bash
        execution:
          onExecute:
            - printenv
      - name: step2aftests
        type: Bash
        configuration:
          inputSteps:
            - name: step1aftests
        execution:
          onExecute:
            - echo 'success'
            - exit 1
