pipelines:
  - name: stepsFour
    steps:
      - name: step1aftests
        type: Bash
        execution:
          onExecute:
            - printenv
      - name: step2aftests
        type: Bash
        configuration:
          inputSteps:
            - name: step1aftests
        execution:
          onExecute:
            - echo 'success'
      - name: step3aftests
        type: Bash
        configuration:
          inputSteps:
            - name: step1aftests
        execution:
          onExecute:
            - echo 'success'
      - name: step4aftests
        type: Bash
        configuration:
          inputSteps:
            - name: step2aftests
            - name: step3aftests
        execution:
          onExecute:
            - echo 'success'          
